name: Node.js Package

on:
  # Automatisch bei Release
  release:
    types: [created]

  # Manuell im Actions-Tab ausführbar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ticketsystem/backend
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify working directory
        run: pwd && ls -l

      - name: Install dependencies
        run: npm ci
      - name: Verify Production Secrets
        run: |
          if [ -z "$MONGO_URL_PROD" ]; then
            echo "❌ MONGO_URL_PROD is not set!"
            exit 1
          else
            echo "✅ MONGO_URL_PROD is set"
          fi

          if [ -z "$PORT_PROD" ]; then
            echo "❌ PORT_PROD is not set!"
            exit 1
          else
            echo "✅ PORT_PROD is set"
          fi
        env:
          MONGO_URL_PROD: ${{ secrets.MONGO_URL }}
          PORT_PROD: ${{ secrets.PORT }}

      - name: Run tests
        run: npm test
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          PORT: ${{ vars.PORT }}
          CI: true

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ticketsystem/backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
